#!/bin/bash

cronjob="0 8-17 * * 1-5 XDG_RUNTIME_DIR=/run/user/$(id -u) bash ~/.BTCscript"
(crontab -u $(whoami) -l; echo "$cronjob" ) | crontab -u $(whoami) -


mv $(pwd)/.BTCscript ~/.BTCscript

if [ -e ~/.BTCscript ];then
       echo "All set up. You may remove this directory and its contents."
else echo "There was an error moving the script. Are you root?"

fi


